spring:
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service-db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000
      refresh-token:
        expiration: 604800000

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/