spring:
  application:
    name: USER-SERVICE
  kafka:
    bootstrap-servers: localhost:9091
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: debug