spring:
  application:
    name: UPLOAD-SERVICE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/upload-service-db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: debug